//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAF.MsgContainer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OperationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAF.MsgContainer.OperationMessages", typeof(OperationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the current operation?.
        /// </summary>
        internal static string CancelConfirmation {
            get {
                return ResourceManager.GetString("CancelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to discard the current changes?.
        /// </summary>
        internal static string ClearConfirmation {
            get {
                return ResourceManager.GetString("ClearConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close this form?.
        /// </summary>
        internal static string CloseConfirmation {
            get {
                return ResourceManager.GetString("CloseConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete this item. &lt;br /&gt;It cannot be restored at a later time! Continue?.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information deleted successfully..
        /// </summary>
        internal static string DeleteOperation {
            get {
                return ResourceManager.GetString("DeleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select data to perform the operation.
        /// </summary>
        internal static string DeleteOrUpdateWithoutSelection {
            get {
                return ResourceManager.GetString("DeleteOrUpdateWithoutSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert duplicate information..
        /// </summary>
        internal static string DuplicateInformation {
            get {
                return ResourceManager.GetString("DuplicateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to send the request?.
        /// </summary>
        internal static string FinalSubmitStudent {
            get {
                return ResourceManager.GetString("FinalSubmitStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OTP has been send to your mobile, please confirm that OTP to complete this process..
        /// </summary>
        internal static string OTPRequest {
            get {
                return ResourceManager.GetString("OTPRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to preview the action?.
        /// </summary>
        internal static string PreviewConfirmation {
            get {
                return ResourceManager.GetString("PreviewConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to execute the process?.
        /// </summary>
        internal static string ProcessConfirmation {
            get {
                return ResourceManager.GetString("ProcessConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the selected information, it has been referenced..
        /// </summary>
        internal static string ReferenceConstraint {
            get {
                return ResourceManager.GetString("ReferenceConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been submitted successfully, for result, please forward to Third Party Request Status Page..
        /// </summary>
        internal static string RequestHasbeenSubmitted {
            get {
                return ResourceManager.GetString("RequestHasbeenSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset the form?.
        /// </summary>
        internal static string ResetConfirmation {
            get {
                return ResourceManager.GetString("ResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the information?.
        /// </summary>
        internal static string SaveConfirmation {
            get {
                return ResourceManager.GetString("SaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been saved successfully..
        /// </summary>
        internal static string SaveOperation {
            get {
                return ResourceManager.GetString("SaveOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to send this message?.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information saved successfully..
        /// </summary>
        internal static string SetUpSaveOperation {
            get {
                return ResourceManager.GetString("SetUpSaveOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to show the information?.
        /// </summary>
        internal static string ShowOperation {
            get {
                return ResourceManager.GetString("ShowOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this post as draft?.
        /// </summary>
        internal static string SubmitForDraft {
            get {
                return ResourceManager.GetString("SubmitForDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to submit this post for Review?.
        /// </summary>
        internal static string SubmitForReview {
            get {
                return ResourceManager.GetString("SubmitForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data will be synchronized. Do you want continue?.
        /// </summary>
        internal static string SyncAllFromDB {
            get {
                return ResourceManager.GetString("SyncAllFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data will be cleared. Do you want to continue?.
        /// </summary>
        internal static string SyncReset {
            get {
                return ResourceManager.GetString("SyncReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Scratch Token has been reloaded to your account successfully..
        /// </summary>
        internal static string TokenConsumed {
            get {
                return ResourceManager.GetString("TokenConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your requested token has been booked for payment process..
        /// </summary>
        internal static string TokenPurchase {
            get {
                return ResourceManager.GetString("TokenPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the selected information?.
        /// </summary>
        internal static string UpdateConfirmation {
            get {
                return ResourceManager.GetString("UpdateConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information updated successfully..
        /// </summary>
        internal static string UpdateOperation {
            get {
                return ResourceManager.GetString("UpdateOperation", resourceCulture);
            }
        }
    }
}
